In [1]:
import pandas as pd

In [4]:
user_to_user_time_series_C0_C1_C2 = pd.read_csv('KeyWords_New/user_to_user_time_series_C0_C1_C2.csv')
user_to_user_time_series_C3_C4 = pd.read_csv('KeyWords_New/user_to_user_time_series_C3_C4.csv')
user_to_user_time_series_C5_C6_C9 = pd.read_csv('KeyWords_New/user_to_user_time_series_C5_C6_C9.csv')

In [5]:
user_to_user_time_series_C0_C1_C2

,dst,src,messages_sent,messages_received,messages_total,contribution_index,start_time_,end_time_
0,a7madness1,a7madness1,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
1,jrbrodin,aasianbokep2,0,1,1,-1.0,2021-11-07 00:00:00,2021-11-08 00:00:00
2,mauri_0fficial,aew,0,1,1,-1.0,2021-11-07 00:00:00,2021-11-08 00:00:00
3,declanjoyce9,aimingtoplease1,0,2,2,-1.0,2021-11-07 00:00:00,2021-11-08 00:00:00
4,akiramakkuro,akiramakkuro,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
...,...,...,...,...,...,...,...,...
152064,zerokdefi,zerokdefi,1,1,2,0.0,2021-11-15 00:00:00,2021-11-16 00:00:00
152065,julienrieutort,julienrieutort,1,1,2,0.0,2021-11-15 00:00:00,2021-11-16 00:00:00
152066,societygurs,societygurs,1,1,2,0.0,2021-11-15 00:00:00,2021-11-16 00:00:00
152067,trading_peter,trading_peter,1,1,2,0.0,2021-11-18 00:00:00,2021-11-19 00:00:00
152068,mumetrdr,mumetrdr,1,1,2,0.0,2021-11-18 00:00:00,2021-11-19 00:00:00

In [6]:
user_to_user_time_series_C3_C4

,dst,src,messages_sent,messages_received,messages_total,contribution_index,start_time_,end_time_
0,2u6ouraiigvilac,2u6ouraiigvilac,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
1,_akutagawa_crow,_akutagawa_crow,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
2,_army_mys,_army_mys,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
3,_just_sae_,_just_sae_,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
4,_musky,_musky,1,1,2,0.0,2021-11-07 00:00:00,2021-11-08 00:00:00
...,...,...,...,...,...,...,...,...
115090,getbrendanjames,cryptochicken7,0,1,1,-1.0,2021-12-13 00:00:00,2021-12-14 00:00:00
115091,casusbellii,casusbellii,1,1,2,0.0,2021-11-16 00:00:00,2021-11-17 00:00:00
115092,nintendofrance,nintendofrance,1,1,2,0.0,2021-11-19 00:00:00,2021-11-20 00:00:00
115093,kthtaexzx,kthtaexzx,1,1,2,0.0,2021-11-19 00:00:00,2021-11-20 00:00:00
115094,15socl,15socl,1,1,2,0.0,2021-11-17 00:00:00,2021-11-18 00:00:00

In [7]:
user_to_user_time_series_C5_C6_C9

,dst,src,messages_sent,messages_received,messages_total,contribution_index,sentiment_avg,emotionality_avg,complexity_avg,start_time_,end_time_
0,5000spacealien1,5000spacealien1,4,4,8,0.0,0.189043,0.242921,5.606178,2021-11-07 00:00:00,2021-11-08 00:00:00
1,ricardomdias1,5000spacealien1,0,1,1,-1.0,NaN,NaN,NaN,2021-11-07 00:00:00,2021-11-08 00:00:00
2,_akutagawa_crow,_akutagawa_crow,1,1,2,0.0,0.062598,0.310250,8.054941,2021-11-07 00:00:00,2021-11-08 00:00:00
3,complexcon,a2stateoftheart,1,0,1,1.0,0.511000,0.191420,4.081273,2021-11-07 00:00:00,2021-11-08 00:00:00
4,a_osumuo,a_osumuo,1,1,2,0.0,0.992839,0.372087,4.438533,2021-11-07 00:00:00,2021-11-08 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...
123393,nintendofrance,nintendofrance,1,1,2,0.0,0.947727,0.392259,8.507692,2021-11-19 00:00:00,2021-11-20 00:00:00
123394,kthtaexzx,kthtaexzx,1,1,2,0.0,0.549364,0.098448,12.211319,2021-11-19 00:00:00,2021-11-20 00:00:00
123395,15socl,15socl,1,1,2,0.0,0.652456,0.121878,8.012346,2021-11-17 00:00:00,2021-11-18 00:00:00
123396,joao__parker,joao__parker,1,1,2,0.0,0.018788,0.212242,5.136730,2021-11-17 00:00:00,2021-11-18 00:00:00
123397,julienrieutort,julienrieutort,1,1,2,0.0,0.976013,0.213775,6.591309,2021-11-15 00:00:00,2021-11-16 00:00:00