In [1]:
import pandas as pd

In [2]:
network_time_series = pd.read_csv('network_time_series.csv')
network_time_series

    number_of_edges  number_of_nodes          start_time_            end_time_
0               133               51  2021-10-22 00:00:00  2021-10-29 00:00:00
1                 7                3  2021-04-09 00:00:00  2021-04-16 00:00:00
2                 3                2  2020-09-25 00:00:00  2020-10-02 00:00:00
3                18                6  2021-10-01 00:00:00  2021-10-08 00:00:00
4                 3                2  2021-05-07 00:00:00  2021-05-14 00:00:00
5                34               13  2021-11-12 00:00:00  2021-11-19 00:00:00
6                 3                2  2020-11-20 00:00:00  2020-11-27 00:00:00
7                 6                3  2021-05-28 00:00:00  2021-06-04 00:00:00
8                 4                3  2021-07-30 00:00:00  2021-08-06 00:00:00
9                11                6  2021-09-10 00:00:00  2021-09-17 00:00:00
10                3                2  2021-08-20 00:00:00  2021-08-27 00:00:00
11                3                2  2021-08-13 00:00:00  2021-08-20 00:00:00
12                6                3  2021-09-17 00:00:00  2021-09-24 00:00:00
13                6                3  2021-03-26 00:00:00  2021-04-02 00:00:00
14            44227            10137  2021-12-03 00:00:00  2021-12-10 00:00:00
15                3                2  2021-06-11 00:00:00  2021-06-18 00:00:00
16               31               12  2021-10-15 00:00:00  2021-10-22 00:00:00
17               92               33  2021-11-19 00:00:00  2021-11-26 00:00:00
18                3                2  2021-03-12 00:00:00  2021-03-19 00:00:00
19            44019             9313  2021-11-05 00:00:00  2021-11-12 00:00:00
20                3                2  2021-06-04 00:00:00  2021-06-11 00:00:00
21                4                3  2020-02-21 00:00:00  2020-02-28 00:00:00
22               11                6  2021-09-24 00:00:00  2021-10-01 00:00:00
23                3                2  2021-07-09 00:00:00  2021-07-16 00:00:00
24                8                5  2021-06-25 00:00:00  2021-07-02 00:00:00
25                3                2  2021-04-02 00:00:00  2021-04-09 00:00:00
26                7                4  2021-09-03 00:00:00  2021-09-10 00:00:00
27                6                3  2021-08-27 00:00:00  2021-09-03 00:00:00
28            58559            12617  2021-10-29 00:00:00  2021-11-05 00:00:00
29                3                2  2020-07-03 00:00:00  2020-07-10 00:00:00
30                6                3  2021-07-16 00:00:00  2021-07-23 00:00:00
31            42103             9103  2021-11-26 00:00:00  2021-12-03 00:00:00
32                3                2  2020-04-24 00:00:00  2020-05-01 00:00:00
33               12                5  2021-10-08 00:00:00  2021-10-15 00:00:00
34                3                2  2021-02-05 00:00:00  2021-02-12 00:00:00

In [3]:
nodes = pd.read_csv('nodes.csv')
nodes

,id,favourites_count,followers_count,statuses_count,friends_count,twitter_query,name,original_dataset,listed_count,messages_sent,...,reach_2_out,reach_2,community_id,sentiment_avg,emotionality_avg,complexity_avg,betweenness,closeness,cluster,contribution_index_oscillation
0,0the_real_devil,16267,1205,11262,1094,BTC,LUCIFER 👑DANNY_FIRST_SON🧸👻,fetcher _ 20211128_BTC _ 20211128_BTC,8,1,...,28876,28877,community_1653,0.292684,0.144223,5.216487,0.000000,0.450283,cluster_1,0
1,0xblackwell,57,5,16,29,BTC,0xBlackwell,fetcher _ 20211128_BTC _ 20211128_BTC,0,1,...,28877,28877,community_1653,0.645656,0.148896,6.264551,235.647541,0.450294,cluster_1,0
2,15ugav9sfvufeps,351,13,264,42,BTC,Рост Ростовский,fetcher _ 20211128_BTC _ 20211128_BTC,1,1,...,28876,28877,community_1653,0.273811,0.207185,5.191489,0.000000,0.450289,cluster_1,0
3,3rdjanuary2009,2,0,1,246,BTC,A Chancellor on the brink ...,fetcher _ 20211128_BTC _ 20211128_BTC,0,1,...,28877,28877,community_1653,0.497630,0.163317,8.035519,1254.478261,0.450294,cluster_1,0
4,__cmc,14531,1909,10783,1090,BTC,Kadena Maxist ⛓🕸,fetcher _ 20211205_BTC _ 20211205_BTC,7,1,...,28877,28877,community_972,0.030062,0.256556,4.811678,28876.000000,0.450294,cluster_1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37057,vgxkronos,1125,143,415,154,BTC,Kronos,fetcher _ 20211128_BTC _ 20211128_BTC,1,1,...,28877,28877,community_1653,0.847652,0.232242,5.104983,14437.500000,0.450294,cluster_1,0
37058,vivianl66831951,1565,520,27719,1533,BTC,Vivian Lewis,fetcher _ 20211205_BTC _ 20211205_BTC,1,1,...,28877,28877,community_1653,0.999176,0.531777,9.827496,1667.075851,0.450310,cluster_1,0
37059,winnietessel,575,100,1083,261,BTC,Winnie,fetcher _ 20211031_BTC _ 20211031_BTC,0,1,...,28876,28877,community_1653,0.645656,0.148896,6.264551,0.000000,0.450294,cluster_1,0
37060,wombat85623246,3423,10,1485,24,BTC,Wombat,fetcher _ 20211128_BTC _ 20211128_BTC,0,1,...,28876,28877,community_1653,0.024840,0.302173,6.488832,0.000000,0.450283,cluster_1,0
37061,xoxoxbanz,5295,203,26409,3135,BTC,🍀XOXO||free tag🍀,fetcher _ 20211031_BTC _ 20211031_BTC,3,1,...,28877,28877,community_1653,0.970673,0.319932,5.692192,73.425258,0.450294,cluster_1,0

In [4]:
time_series = pd.read_csv('time_series.csv')
time_series

# cluster + time stamp is used

,id,favourites_count,followers_count,statuses_count,friends_count,twitter_query,name,original_dataset,listed_count,messages_sent,...,community_id,sentiment_avg,emotionality_avg,complexity_avg,betweenness,closeness,cluster,contribution_index_oscillation,start_time_,end_time_
0,aynenbeeyza,5175,238,2334,243,BTC,beyza.,fetcher _ 20211205_BTC _ 20211205_BTC,5,1,...,community_1653,0.061145,0.304475,11.461567,2061.642857,0.450294,cluster_1,0,2021-12-03 00:00:00,2021-12-10 00:00:00
1,kriptocum4,2586,11702,12462,121,BTC,👑 🅲🆁🆈🅿🆃🅾 🆁🅴🅸🆂 👑,fetcher _ 20211205_BTC _ 20211205_BTC,31,8,...,community_1653,0.775175,0.304228,10.973110,19.708777,0.450327,cluster_1,2,2021-11-26 00:00:00,2021-12-03 00:00:00
2,bitcoinbased,652,143,1189,544,BTC,Bitcoin Based,fetcher _ 20211031_BTC _ 20211031_BTC,4,1,...,community_1653,0.610494,0.158284,5.408799,28876.000000,0.450300,cluster_0,0,2021-10-29 00:00:00,2021-11-05 00:00:00
3,stacktistic_btc,543,538,463,876,BTC,STACKTISTICS.btc 🎫,fetcher _ 20211205_BTC _ 20211205_BTC,8,8,...,community_1653,0.555073,0.165025,5.106082,188661.166667,0.450393,cluster_2,0,2021-12-03 00:00:00,2021-12-10 00:00:00
4,opporeno2,11208,296,4080,815,BTC,比特币-百舸争流,fetcher _ 20211031_BTC _ 20211031_BTC,5,2,...,community_1653,0.645656,0.148896,6.264551,9624.666667,0.450294,cluster_1,0,2021-10-29 00:00:00,2021-11-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41356,btc_bomber,0,0,0,0,BTC,桜囲章一⚛️仮想通貨,fetcher _ 20211205_BTC _ 20211205_BTC,0,0,...,community_2720,NaN,NaN,NaN,0.000000,0.000000,cluster_1,0,2021-12-03 00:00:00,2021-12-10 00:00:00
41357,scooterdawg,0,0,0,0,BTC,Kevin B. #KeepVirginiaBlue,fetcher _ 20211031_BTC _ 20211031_BTC,0,0,...,community_395,NaN,NaN,NaN,0.000000,0.000000,cluster_0,0,2021-10-29 00:00:00,2021-11-05 00:00:00
41358,xshibanu,0,0,0,0,BTC,XShibanu,fetcher _ 20211205_BTC _ 20211205_BTC,0,0,...,community_1653,NaN,NaN,NaN,0.000000,0.000000,cluster_1,0,2021-11-26 00:00:00,2021-12-03 00:00:00
41359,cryptoboyka1,0,0,0,0,BTC,Crypto Boyka,fetcher _ 20211107_BTC_20211107_BTC,0,1,...,community_1653,0.930703,0.386621,8.652434,0.000000,0.450283,cluster_1,0,2021-11-05 00:00:00,2021-11-12 00:00:00
41360,beamarq14614987,0,0,0,0,BTC,Bea Marquez,fetcher _ 20211205_BTC _ 20211205_BTC,0,0,...,community_530,NaN,NaN,NaN,0.000000,0.000000,cluster_1,0,2021-12-03 00:00:00,2021-12-10 00:00:00

In [5]:
time_series["cluster"].unique()

array(['cluster_1', 'cluster_0', 'cluster_2'], dtype=object)

In [6]:
user_to_user = pd.read_csv('user_to_user.csv')
user_to_user

,src,dst,messages_sent,messages_received,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges
0,0xgianni,coingecko,1,0,1,1.0,NaN,NaN,NaN,NaN
1,0xr2_,rektcapital,1,0,1,1.0,NaN,NaN,NaN,NaN
2,13thcryptotitan,13thcryptotitan,1,1,2,0.0,NaN,NaN,NaN,NaN
3,21_millie_btc,[twitter_query=btc],1,1,2,0.0,NaN,NaN,0.0,1.0
4,2bosquez4,2bosquez4,1,1,2,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
168811,yy55088169,cryptofinally,1,0,1,1.0,NaN,NaN,NaN,NaN
168812,zgrdurm92493156,eskiyeniyatirim,1,0,1,1.0,NaN,NaN,NaN,NaN
168813,zidanezizo122,mhmdgenral,0,2,2,-1.0,NaN,NaN,NaN,NaN
168814,zuri05622973,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN
168815,zzbkmzz,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN

In [7]:
user_to_user_time_series = pd.read_csv('user_to_user_time_series.csv')
user_to_user_time_series

# adjacency matrix
# x-axis = dst
# y-axis = src
# z-axis = time_series

,src,dst,messages_sent,messages_received,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges,sentiment_avg,emotionality_avg,complexity_avg,start_time_,end_time_
0,beconomy_hq,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.836148,0.281494,5.119517,2020-02-21 00:00:00,2020-02-28 00:00:00
1,truthraiderhq,beconomy_hq,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-21 00:00:00,2020-02-28 00:00:00
2,beconomy_hq,beconomy_hq,1,1,2,0.0,NaN,NaN,NaN,NaN,0.836148,0.281494,5.119517,2020-02-21 00:00:00,2020-02-28 00:00:00
3,beconomy_hq,truthraiderhq,1,0,1,1.0,NaN,NaN,NaN,NaN,0.836148,0.281494,5.119517,2020-02-21 00:00:00,2020-02-28 00:00:00
4,[twitter_query=btc],beconomy_hq,1,1,2,0.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,2020-02-21 00:00:00,2020-02-28 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175590,trading_peter,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.838159,0.193055,5.924200,2021-11-12 00:00:00,2021-11-19 00:00:00
175591,dogsofelon,dogsofelon,1,1,2,0.0,NaN,NaN,NaN,NaN,0.639133,0.121849,5.240852,2021-11-12 00:00:00,2021-11-19 00:00:00
175592,santa_coins,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.991211,0.295401,6.576543,2021-11-12 00:00:00,2021-11-19 00:00:00
175593,armando_aml,armando_aml,1,1,2,0.0,NaN,NaN,NaN,NaN,0.958465,0.198134,6.362594,2021-11-12 00:00:00,2021-11-19 00:00:00
175594,cryptokunstler,cryptokunstler,1,1,2,0.0,NaN,NaN,NaN,NaN,0.928048,0.276091,9.097756,2021-11-12 00:00:00,2021-11-19 00:00:00

In [44]:
user_to_user_time_series[user_to_user_time_series['src'] == 'btc_magazin']['dst']

1217         hadibagaym_2
3363        burak27833853
3364             krks1987
3627              binance
5020            brk35klnc
               ...
156438    sampiyonlukbek1
159246         xpehlivanx
160373        mahmuttuzen
167271           waffen97
174819           srhtekms
Name: dst, Length: 504, dtype: object

In [29]:
for index, row in adj_mat_df_cols.iterrows():
    print(user_to_user_time_series[user_to_user_time_series['src'] == index]['dst'])

55012    [twitter_query=btc]
55876               sma_sare
91986            aynenbeeyza
Name: dst, dtype: object
22330              kriptocum4
31271     [twitter_query=btc]
55751     [twitter_query=btc]
59152              kriptocum4
78065         zgrdurm92493156
86953             btc_magazin
95058           yunus76880937
97922           antcarconcept
101798          serkanzazavaj
105477             buketunsel
106332               tahhar06
108159        mustafa67568754
122532           yigitt_ahmet
123586           masor1010bal
124002    [twitter_query=btc]
126433             kriptocum4
129517            aliduman070
139002             kriptocum4
145678          erychka77girl
147121    [twitter_query=btc]
156667                rrr_btc
158559        muhamme81856807
170696         muhsin98558491
Name: dst, dtype: object
395              btc_archive
2338     [twitter_query=btc]
24432             calvinayre
34135           bitcoinbased
Name: dst, dtype: object
55375         stacktistic_btc
61451     [twitter_query=btc]
65164          openartsource1
65780                  stacks
73985              miamisanti
77038           minecitycoins
80864                  cdixon
89584             mannymoe707
90704              curatorbtc
97578                  stxnft
146070            artonstacks
146642                karl_zw
155630               boozybtc
161574                 stacks
167730          cryptospia_it
170387        stacktistic_btc
170750    [twitter_query=btc]
172382         abdull45001583
174569             jk43749392
Name: dst, dtype: object
799                  btw0205
3228               opporeno2
49989    [twitter_query=btc]
Name: dst, dtype: object
706          liamblockchains
29046    [twitter_query=btc]
36636               coochm11
50445                shibsol
Name: dst, dtype: object
98130              sultanguss
100577               humblpay
105082    [twitter_query=btc]
128901         humblwarrior81
Name: dst, dtype: object
1340              mooringaa3
20745    [twitter_query=btc]
21827            borsaeditor
Name: dst, dtype: object
1322     [twitter_query=btc]
13359              galaxybtc
44669           magggiiiieee
Name: dst, dtype: object
139571    [twitter_query=btc]
154138           maxxchewning
Name: dst, dtype: object
139746    [twitter_query=btc]
149481            btc_archive
158361           crypt0trader
168907               jektonft
Name: dst, dtype: object
55997         thakordashrat80
65552         sarahsm68204407
65756                 binance
65978              cz_binance
70276     [twitter_query=btc]
74184          baby_doarchive
94691               qanda7272
95984            babydogecoin
154156    [twitter_query=btc]
170200              qanda7272
172189            babydogboss
Name: dst, dtype: object
98537           dyorcryptobot
119321    [twitter_query=btc]
121500          daviddepaul10
Name: dst, dtype: object
98484         alejandrosacias
102717              bitkeepos
108913          realdasystems
114541    [twitter_query=btc]
Name: dst, dtype: object
139641          35izmirlili35
145415         enginerdoganxu
145732    [twitter_query=btc]
Name: dst, dtype: object
1818          stevedabitcoin
24756                eos1894
36121           berkayozdinc
50184    [twitter_query=btc]
Name: dst, dtype: object
56537    [twitter_query=btc]
80953            luckycorgis
83060            clementwoof
Name: dst, dtype: object
56604             whalestats
76352              mamat_cil
83119    [twitter_query=btc]
Name: dst, dtype: object
56568            giet_maul16
77160    [twitter_query=btc]
81800            paulroadman
Name: dst, dtype: object
99121           willywonkaxrp
122849    [twitter_query=btc]
124941           bill09945892
Name: dst, dtype: object
56627             paulroadman
62493     [twitter_query=btc]
67715             thedefijedi
67915             okkasarry12
99428         thanosgemhunter
126057            okkasarry12
136569    [twitter_query=btc]
Name: dst, dtype: object
2663           hafeezzargar4
22298               richshib
45187    [twitter_query=btc]
46372          shibainfinity
Name: dst, dtype: object
56780    [twitter_query=btc]
82628           drlovenstein
Name: dst, dtype: object
56944              andrads30
68450            thedefijedi
79665         moonshot_calls
87522    [twitter_query=btc]
Name: dst, dtype: object
99644             scorpions_t
132719    [twitter_query=btc]
146631    [twitter_query=btc]
168241            scorpions_t
Name: dst, dtype: object
22015         cot_criptomoeda
47739     [twitter_query=btc]
57637         cot_criptomoeda
87983     [twitter_query=btc]
99550         cot_criptomoeda
116068    [twitter_query=btc]
Name: dst, dtype: object
57260        luckyybanggarrr
65726    [twitter_query=btc]
94040            paulroadman
Name: dst, dtype: object
3224         o52yl11fwciper5
44139              gojogojou
50272    [twitter_query=btc]
Name: dst, dtype: object
100053            twetch40880
117009                 crypto
129390    [twitter_query=btc]
Name: dst, dtype: object
3465          mz_silenttearz
35348            cryptoboltx
41155    [twitter_query=btc]
53823             bonustiime
Name: dst, dtype: object
57698                smhdoge
68743    [twitter_query=btc]
96943        mavishfernande1
Name: dst, dtype: object
58134             pashankara
76816    [twitter_query=btc]
78309          kriptomevsimi
81665             logostrade
Name: dst, dtype: object
141687         drogondrakarys
157342          futuristicgen
161881    [twitter_query=btc]
Name: dst, dtype: object
141954        winscityx112990
148995           shiborgtoken
166449    [twitter_query=btc]
Name: dst, dtype: object
4736             birumenangg
8331            rewardsbunny
36614    [twitter_query=btc]
Name: dst, dtype: object
100931             thegradlon
117491         coinacademy_fr
125741        charles46301154
128651               yieldapp
137315    [twitter_query=btc]
Name: dst, dtype: object
19382              robostopia
25700     [twitter_query=btc]
86997              robostopia
87853     [twitter_query=btc]
101257    [twitter_query=btc]
107412             robostopia
160465    [twitter_query=btc]
163080             robostopia
Name: dst, dtype: object
142117             slush_pool
147335    [twitter_query=btc]
162915            thacashous1
Name: dst, dtype: object
142286            skatygarcia
165166    [twitter_query=btc]
Name: dst, dtype: object
5430          ashlee93247466
9852                 orenj0e
41176        cryptotipsking1
43318    [twitter_query=btc]
Name: dst, dtype: object
6686     [twitter_query=btc]
8975         cryptonatical86
51294          cryptodackel1
58898        cryptonatical86
84764              mrportner
88414    [twitter_query=btc]
Name: dst, dtype: object
142199    [twitter_query=btc]
168332         steam_exchange
169040           crypticcityx
Name: dst, dtype: object
58943          orbit_crypto_
79945    [twitter_query=btc]
84357             tommychong
91833         jodin_the_meme
Name: dst, dtype: object
59110    [twitter_query=btc]
87772         crystalraynor5
89015            eventuscoin
Name: dst, dtype: object
101620         matthews_trace
120903    [twitter_query=btc]
130620          willywonkaxrp
Name: dst, dtype: object
5787              zahraa_nia
26010        cryptotweetybee
31657    [twitter_query=btc]
34050         realakamaruinu
36538             inusaitama
Name: dst, dtype: object
142748        dogeofficialceo
156261    [twitter_query=btc]
175008           chaudhry1300
Name: dst, dtype: object
6269           salmenalnemer
16091    [twitter_query=btc]
39517        healthy_pockets
Name: dst, dtype: object
6194             hexstreamers
22850             mangosonly1
25037     [twitter_query=btc]
37544               hexcrypto
57454             nonbinarysj
66800            hexstreamers
94849     [twitter_query=btc]
120663            ds_network_
124186           hexstreamers
131022    [twitter_query=btc]
139168              gerawrdog
144558         havawebhosting
153718            whalesonly1
154466             hexamortis
159488           hexstreamers
162279    [twitter_query=btc]
166199         cryptovince369
Name: dst, dtype: object
6052     [twitter_query=btc]
16153             protonroad
38228                60fps24
Name: dst, dtype: object
59801            luckyhearty
65529    [twitter_query=btc]
86087            thedefijedi
89530         genius_crypto_
Name: dst, dtype: object
102244    [twitter_query=btc]
125655           sougo_shien6
Name: dst, dtype: object
102329            btc_magazin
106883            myteamchain
130966            black_bulll
135675    [twitter_query=btc]
Name: dst, dtype: object

6669                carp1551
26104    [twitter_query=btc]
33107           nftpromotion
Name: dst, dtype: object
6933         benjoesangalang
15705    [twitter_query=btc]
16223               xshibanu
Name: dst, dtype: object
102678           telcoin_team
106618    [twitter_query=btc]
111382               cotykuhn
119875              voodooroo
Name: dst, dtype: object
7245         buddhadevgiri11
33849    [twitter_query=btc]
Name: dst, dtype: object
143536             toxicdegen
154362    [twitter_query=btc]
Name: dst, dtype: object
7395     [twitter_query=btc]
13711            darklightco
19982           thunder_meat
31637          altcoingordon
33005          antoneville07
50329        secretsofcrypto
50876             btcgandalf
53336            jackemson99
Name: dst, dtype: object
143442           cryptonette1
158717           bitbitcrypto
159066    [twitter_query=btc]
Name: dst, dtype: object
60654           rida09240916
71144    [twitter_query=btc]
96788            nftdropscal
Name: dst, dtype: object
103042              gojogojou
122788         serkanarikan06
131108    [twitter_query=btc]
132507            tsuyopon_u3
Name: dst, dtype: object
7562           precogfinance
36990         ashlee93247466
42462             herry_ploo
43251    [twitter_query=btc]
Name: dst, dtype: object
7580             luckycorgis
16596         cryptograndpas
27781            chiwawaswap
42218             kriptoada1
54047    [twitter_query=btc]
Name: dst, dtype: object
151633           bomsteinrick
175481        delta____wither
175543    [twitter_query=btc]
Name: dst, dtype: object
7925     [twitter_query=btc]
26767          risma92758840
46452             bitcoincom
Name: dst, dtype: object
103443             tastyworks
109939         shibainutoken_
137228    [twitter_query=btc]
Name: dst, dtype: object
8126     [twitter_query=btc]
10070        hungarian_bitch
42464            dickcoin_io
42729              mooigirlz
48067               p_orn_69
Name: dst, dtype: object
8161              mdagli2003
22096          rayndalcrypto
38134    [twitter_query=btc]
Name: dst, dtype: object
7989                elonmusk
39282    [twitter_query=btc]
46529          1903noiraigle
Name: dst, dtype: object
144413         mtrl_scientist
148958    [twitter_query=btc]
158199               nikbinaz
Name: dst, dtype: object
8642               amihaninj
23328    [twitter_query=btc]
42133        intocryptoverse
Name: dst, dtype: object
9123             time_money_
41226    [twitter_query=btc]
Name: dst, dtype: object
104293            tunakaya_yk
106794             saip_yasar
108650    [twitter_query=btc]
Name: dst, dtype: object
9247     [twitter_query=btc]
27726              dorayan_f
Name: dst, dtype: object
9238              ucfinance1
41889           cryptowisper
42952    [twitter_query=btc]
Name: dst, dtype: object
144714              bonker507
150533            cunoarslann
152760          deniz76829428
162252    [twitter_query=btc]
165980          kriptozenciii
167659           giannismoney
Name: dst, dtype: object
9342          roadtoserfdom3
21045    [twitter_query=btc]
36779           jozzimevozzi
48149        btc_pa_analysis
Name: dst, dtype: object
717       stockwa60818438
1514        bearmarketbtc
6441              jst8cks
6695            morphism_
8690       camara04302477
               ...
143995    mitchel31542927
146174      johnhumeross1
169421         iistrohhut
172845            jouri71
173219       crypto_sk555
Name: dst, Length: 90, dtype: object
9491      [twitter_query=btc]
14390           shibainfinity
15218             shibaricher
35023            darr99962884
155729            themooncarl
157156    [twitter_query=btc]
165265           darr99962884
Name: dst, dtype: object
9518     [twitter_query=btc]
36399           mkid12276995
39405             gfahim1982
Name: dst, dtype: object
145047    [twitter_query=btc]
148516             coinmatik1
165632         brazilamericas
Name: dst, dtype: object
10123            realyoyowbu
12566    [twitter_query=btc]
18503         nofear07860922
Name: dst, dtype: object
104838            pitbullhodl
118913               coin100_
133434    [twitter_query=btc]
137715           pitbullchart
Name: dst, dtype: object
62711    [twitter_query=btc]
77223           rasonlytrade
Name: dst, dtype: object
145499               xtrendci
155536            efecelikler
173940    [twitter_query=btc]
Name: dst, dtype: object
62941              btcpaytkn
92806    [twitter_query=btc]
96189            runescrypto
Name: dst, dtype: object
62928    [twitter_query=btc]
95741             putramosap
Name: dst, dtype: object
105312                btc_nft
112826            uniswap_gem
118184            rendy_sanja
126275    [twitter_query=btc]
131088              jaemcityx
135588            block_flash
Name: dst, dtype: object
10638         mattwallace888
22311            janstabares
23696               elonmusk
41936    [twitter_query=btc]
Name: dst, dtype: object
63520            thedefijedi
71900    [twitter_query=btc]
92461            dwi_adhliza
Name: dst, dtype: object
63759              izumifaiz
75882             nft_yooshi
79084    [twitter_query=btc]
Name: dst, dtype: object
63964            e1liotrades
84110    [twitter_query=btc]
90794            elliotrades
Name: dst, dtype: object
64181    [twitter_query=btc]
66120         genius_crypto_
79922           gldnbluedeep
Name: dst, dtype: object
146735    [twitter_query=btc]
173209         coudronmattias
173577          axion_network
Name: dst, dtype: object
12277           lelawati1502
35077    [twitter_query=btc]
40315           rewardsbunny
Name: dst, dtype: object
64192           john57075146
75889    [twitter_query=btc]
94232          orbit_crypto_
Name: dst, dtype: object
106669            btc_archive
116656              bengbills
123278    [twitter_query=btc]
Name: dst, dtype: object
146942    [twitter_query=btc]
163611              leone4812
175237                ekoncaa
Name: dst, dtype: object
12652          shibainfinity
26011    [twitter_query=btc]
43390                zaqpar1
Name: dst, dtype: object
12560           naimsetiyono
24256    [twitter_query=btc]
49978                shibsol
Name: dst, dtype: object
146940          kuntarsih_kun
169984    [twitter_query=btc]
171248               k_poblah
Name: dst, dtype: object
146923                  santa
151457           issa93363656
172694    [twitter_query=btc]
Name: dst, dtype: object
13362               elonmusk
19632        mattymoostahot1
22617               coinkoda
42237        mahmoud67953798
45242                 kceoda
49448    [twitter_query=btc]
Name: dst, dtype: object
107430    [twitter_query=btc]
118199              mand01off
125879         serkanarikan06
130021              tmanar278
Name: dst, dtype: object
13716             terrapadtp
40393    [twitter_query=btc]
47901                tsabut2
Name: dst, dtype: object
13911          magsino_jorge
22092    [twitter_query=btc]
38644           cryptocards_
47817                airnfts
Name: dst, dtype: object
107702                blg_cnr
107703             terrapadtp
107893    [twitter_query=btc]
Name: dst, dtype: object
13821                    jack
44020     [twitter_query=btc]
45438            bsvbulldoggy
146338            daniel_dct3
162052             dk11125292
Name: dst, dtype: object
13909              mabu_2001
40060    [twitter_query=btc]
Name: dst, dtype: object
14142            bitorbitapp
24184                btc_nft
29884                 fandmt
42444          divineanarchy
51025    [twitter_query=btc]
Name: dst, dtype: object
101683         arvind63141967
102045          futureprintye
106608          degnonganlaky
108434         ttcoinofficial
108856        wasimsh17115563
113636                 rtvk76
114469        eduardovlotoski
115118        nityana59781234
130898          alsudi_box_tv
134828         mdsaim39486136
138247    [twitter_query=btc]
144622             sulu_mercy
162721        juliocarneiro17
Name: dst, dtype: object
14703         ashlee93247466
23693    [twitter_query=btc]
44635            ikaariati05
Name: dst, dtype: object
66394         miloszmichalak
78491    [twitter_query=btc]
87822           everdomehero
Name: dst, dtype: object
66346           jeremycrypt0
78863    [twitter_query=btc]
92240                ffyxiii
Name: dst, dtype: object
10691           oldtraderpro
16367           thekriptolik
22643    [twitter_query=btc]
23205         cakirbeynusret
23749           kriptocapris
45545             ekoanalizz
46721           eness_turann
51914         mattwallace888
66403    [twitter_query=btc]
67067           oldtraderpro
Name: dst, dtype: object
108547    [twitter_query=btc]
119545               dhebdudb
137149        gremlinsfinance
Name: dst, dtype: object

66746               bigwin30
88580         genius_crypto_
88792    [twitter_query=btc]
88793         moonshot_calls
Name: dst, dtype: object
66771              delvaco75
75419              btcpaytkn
81995            luckycorgis
86232    [twitter_query=btc]
Name: dst, dtype: object
149116            lamb_crypto
164536          cryptoforce_1
168199    [twitter_query=btc]
Name: dst, dtype: object
149072    [twitter_query=btc]
171383             crypto1923
Name: dst, dtype: object
66972           champ_corner
76506           mkid12276995
93977    [twitter_query=btc]
Name: dst, dtype: object
16016    [twitter_query=btc]
19003                nzensin
44079           hanamaruline
Name: dst, dtype: object
67295    [twitter_query=btc]
73505                smhdoge
73745                phtechy
83979              hulkordie
Name: dst, dtype: object
8104             bookbookkoji
15992     [twitter_query=btc]
43505            emel95218388
104428           emel95218388
138147    [twitter_query=btc]
Name: dst, dtype: object
16245            rewardsbunny
40242     [twitter_query=btc]
49881               chae_ilya
157142    [twitter_query=btc]
159252           shiborgtoken
161289              chae_ilya
Name: dst, dtype: object
149500    [twitter_query=btc]
165524          mjsportscards
Name: dst, dtype: object
16516    [twitter_query=btc]
36936                twds_jp
51273          btc_hottemasu
Name: dst, dtype: object
16598    [twitter_query=btc]
28345              lamoirade
28604             bonustiime
51888            cryptoboltx
Name: dst, dtype: object
149626    [twitter_query=btc]
170482          deadsh0rtxf3r
174111           damien92_nft
Name: dst, dtype: object
109945    [twitter_query=btc]
112012            spartacus0x
138862         isimsiz_trader
Name: dst, dtype: object
16614    [twitter_query=btc]
20194              betfuryid
36744              morochor9
Name: dst, dtype: object
67888        ksvdvwmwlkvcvul
88237    [twitter_query=btc]
96356           reonaokiriri
Name: dst, dtype: object
16826    [twitter_query=btc]
31230               exitlayt
34758             traderli0n
Name: dst, dtype: object
67964              fegfannek
72245               fegtoken
77486           ateitis_corp
84435                 300zxt
95355    [twitter_query=btc]
95579              fegplutos
Name: dst, dtype: object
110775                bigwhle
114254    [twitter_query=btc]
117804         shillywilly747
Name: dst, dtype: object
68442            eventuscoin
73604                adaldds
78180    [twitter_query=btc]
Name: dst, dtype: object
150623              tulavega_
170573    [twitter_query=btc]
Name: dst, dtype: object
68896              durriyeii
69142    [twitter_query=btc]
74543            eventuscoin
Name: dst, dtype: object
111288    [twitter_query=btc]
115470            luckycorgis
137536             gamerlicia
Name: dst, dtype: object
18840           tigerblack75
24320    [twitter_query=btc]
35424          abdulkerimsma
Name: dst, dtype: object
69401         metagalaxyland
70894         mahditeymouri6
89073    [twitter_query=btc]
Name: dst, dtype: object
66963          genius_crypto_
68463     [twitter_query=btc]
84499                bii8_boo
87963               kaylertee
111664    [twitter_query=btc]
125337               bii8_boo
125728        thanosgemhunter
Name: dst, dtype: object
69768                  0xzak
86908           dmtboofdaddy
97482    [twitter_query=btc]
Name: dst, dtype: object
19712          tradeboy_offl
22689    [twitter_query=btc]
Name: dst, dtype: object
19684    [twitter_query=btc]
33232             terrapadtp
44446        shankorchandra4
Name: dst, dtype: object
19666    [twitter_query=btc]
41705             daancrypto
48405        pimientajoelana
Name: dst, dtype: object
112512    [twitter_query=btc]
115665                 btc_xx
120394                 d3li14
Name: dst, dtype: object
70657    [twitter_query=btc]
83516            eventuscoin
91630               iemakar1
Name: dst, dtype: object
112853    [twitter_query=btc]
113049          yunus57520418
136821             dixitrader
Name: dst, dtype: object
152378              cryptox84
163002            themooncarl
172296    [twitter_query=btc]
Name: dst, dtype: object
152421              lilselcuk
166399    [twitter_query=btc]
167322            ferhatsanli
Name: dst, dtype: object
69857              tin1trader
75757         cryptoposeidonn
91315     [twitter_query=btc]
113235    [twitter_query=btc]
117810             tin1trader
141769             tin1trader
143365        dominiklupinski
153036               lacmessi
164592            liuluoxi152
165893        gabe_gs_sanchez
167912    [twitter_query=btc]
Name: dst, dtype: object
21209     [twitter_query=btc]
23109           cryptodolphyn
55030            leventcakir_
58695             btc_magazin
58896            teknikcihoca
72535              gokhangark
74766            kriptolevent
76945          stevedabitcoin
88809           cryptodolphyn
90598         ragnarthesurfer
92899           hasosyalmedya
96094     [twitter_query=btc]
141486               feryat16
141487               tt_forex
145482           serbestmasam
151812                gmgiray
156628              kalfore34
164683          cryptodolphyn
169610            lucky_boss_
173213    [twitter_query=btc]
Name: dst, dtype: object
152900              curfewgad
155860          _judgecrypto_
172990    [twitter_query=btc]
Name: dst, dtype: object
113625            byscarface1
114247    [twitter_query=btc]
114657         coindoktorunuz
131093           salihclk3449
Name: dst, dtype: object
113550    [twitter_query=btc]
124780        francis94981451
130787          mooncatcrypto
Name: dst, dtype: object
71588             shib_power
78332    [twitter_query=btc]
78333               gigicryp
Name: dst, dtype: object
2100          samthecarpetman
35837     [twitter_query=btc]
37524             frankcneroo
113750    [twitter_query=btc]
121727             travalacom
126208            frankcneroo
Name: dst, dtype: object
153404    [twitter_query=btc]
166049                pljuhar
166419               nfaliens
Name: dst, dtype: object
113926            myteamchain
127395             bluetutu88
128053            btc_magazin
132811    [twitter_query=btc]
Name: dst, dtype: object
153279             rc_signals
168307    [twitter_query=btc]
168845          arcan10591704
Name: dst, dtype: object
22178             terrapadtp
24337    [twitter_query=btc]
39022           yakupgvercin
Name: dst, dtype: object
22181             yosefejigu
27600             bonustiime
32759    [twitter_query=btc]
37115            cryptoboltx
Name: dst, dtype: object
114184            julesurbach
120422           huskybluesky
127906              wearerndr
130801        btc__blockchain
133870    [twitter_query=btc]
Name: dst, dtype: object
72343            thedefijedi
83280              dincityxx
92713    [twitter_query=btc]
Name: dst, dtype: object
22825    [twitter_query=btc]
24744        drinkmytear24_7
43227            whale_alert
Name: dst, dtype: object
115027         ttcoinofficial
118523    [twitter_query=btc]
126616          futureprintye
Name: dst, dtype: object
24412    [twitter_query=btc]
25572          divineanarchy
34688         allisoncrypto1
35235            bitorbitapp
49067                btc_nft
Name: dst, dtype: object
15441            deep63132948
19514             poodlympics
24707     [twitter_query=btc]
47444            crypt0crypto
49871         bitcoin22109717
50977            yous60965764
102728    [twitter_query=btc]
108727        bitcoin22109717
111665          b055lady_elle
134243            poodletoken
147071            byroncallon
148895             crypt0glrl
166855           crypt0crypto
Name: dst, dtype: object
25325     [twitter_query=btc]
45778               kahinbey0
48603            farukztekin8
51587            eness_turann
128099           farukztekin8
131380              kahinbey0
135522    [twitter_query=btc]
143825           farukztekin8
151650        powerhourtrades
154640           rafet__meric
169802    [twitter_query=btc]
171028          isimsoyisimde
Name: dst, dtype: object
25420    [twitter_query=btc]
28645               richshib
34844          shibainfinity
53291             pratikn177
54888           lilliemicroc
Name: dst, dtype: object
26441    [twitter_query=btc]
30753          shibainfinity
35326            shibaricher
51368                 l3saku
Name: dst, dtype: object
75724    [twitter_query=btc]
88890          mandingoridge
94683         metbackedmoney
95519            eventuscoin
97558          oding56663700
Name: dst, dtype: object
26862    [twitter_query=btc]
30656               richshib
37461        adisapu40851238
38274          shibainfinity
Name: dst, dtype: object
27181    [twitter_query=btc]
32037        gqtmpl8uc8yurva
33383             cryptocevo
Name: dst, dtype: object
27421              bolziccol
30674            baby_defido
38034    [twitter_query=btc]
Name: dst, dtype: object

118177            btc_archive
130215           pay_investor
137401    [twitter_query=btc]
Name: dst, dtype: object
76994         moonshot_calls
91638    [twitter_query=btc]
97123         koocityxbigwin
Name: dst, dtype: object
119132             hamzorotti
123557            alienworlds
133294    [twitter_query=btc]
Name: dst, dtype: object
119351             hold_trade
125584    [twitter_query=btc]
Name: dst, dtype: object
158491              icedknife
169024            crypto_penn
170293              traderpow
170647            megapontnft
170815    [twitter_query=btc]
174633          blackmambabtc
Name: dst, dtype: object
29749     [twitter_query=btc]
39588             kriptokusuu
52539              47cuneyt47
141241            cunoarslann
148999             47cuneyt47
160871    [twitter_query=btc]
Name: dst, dtype: object
58376                show4653
78942           theo_crypto99
96010     [twitter_query=btc]
116407            bakoski_btc
119228             md92023026
Name: dst, dtype: object
31062          cryptoemre2020
31867         robertd51188384
43870     [twitter_query=btc]
100838        robertd51188384
102225    [twitter_query=btc]
110128           btc_usdt_ltc
Name: dst, dtype: object
121148         mehtap20519923
133355        sefatrk48913436
136182        gems_cryptocoin
137824    [twitter_query=btc]
Name: dst, dtype: object
31603    [twitter_query=btc]
35392         ashlee93247466
41729               seyah_11
Name: dst, dtype: object
17150               kelcrypto
34227             kalamarr003
37838     [twitter_query=btc]
98982                csknpmkc
100188             emre190721
104022                 iskbet
109007             slm___ylmz
109450            canemre5234
109451             guneyerali
116727          yusuf65357793
117342             sa02593436
117940              kelcrypto
118969          mustafaoruc84
121096    [twitter_query=btc]
121545        hseyiny96988277
123998                 berxsx
128532        ramazan11091987
134527             skarabag66
137764        muratya95037369
138587           yucelakkaya7
160600    [twitter_query=btc]
170521           eness_turann
171420              kelcrypto
Name: dst, dtype: object
80790             haienakunn
96126    [twitter_query=btc]
Name: dst, dtype: object
161733              mago_pool
165115    [twitter_query=btc]
Name: dst, dtype: object
81993    [twitter_query=btc]
86903           cryptokojima
89476        cryptow78202593
Name: dst, dtype: object
36457    [twitter_query=btc]
52714           mmustafaelma
Name: dst, dtype: object
83270    [twitter_query=btc]
86441         cryptobullatom
86442             emperorbtc
Name: dst, dtype: object
125773             johalmiles
132859        floreatiberiu01
134936    [twitter_query=btc]
Name: dst, dtype: object
129555    [twitter_query=btc]
136365         obednaltrading
Name: dst, dtype: object
145       [twitter_query=btc]
149               teknikciniz
8557            hayatbubosver
15609             teknikciniz
27307     [twitter_query=btc]
46494          zmnda_yolculuk
55812           alikeskin2546
58372              mehdigider
59003           hozan25988357
59430         muhitti45065941
61892             ali32689778
63402           denizselcuk19
67094             teknikciniz
70297     [twitter_query=btc]
71600               pnarseval
72436              fitzmoneda
74410           fatih19264644
74411            gazikorkmazo
78539          ismail34kara75
78938         emirhan44068321
82092              hacnergiz2
95329              jamiiryouu
96607           kenan28535587
103659        ramazan34796242
117808                ozihkn1
Name: dst, dtype: object
35780            ppnsiva2
97656           arbusheik
97657            hivebloq
98054          cerncrypto
98055        emussame_nft
98496         yazc_serdar
98718       hendarunyil27
98719             ybs0792
99912       josealcazar15
100907         shadow6156
102108       trillyenheir
102536       bblacksaiyan
102724        cryptomar94
103937       soso99581944
104386     diamond_dan007
106875       bicakciali07
108287          mikekalp2
111037        torasan_afi
112098        talha_arac_
112700    marthabumbartha
116041     fatmaacimert53
116867      miftahudinsd9
117067          nakeyynft
117669         glebozavr2
117870         mu97736821
118692        vlad__barbu
121032       joelcrypto11
122270          parlons_p
122458          bysonevil
123075       thetrumandan
123276           jettnoir
124130    iamthe_greatone
125143        paramnerede
126775       bayufirlana5
128629            gjwangj
130743         blupillnft
130960            n_f_t__
131553          tactictot
132154         gr_shiba_n
132369           actut3ch
132800    mdmehed70778720
133044            famin04
134239       murathanifi1
134450       jhonabella22
134451    rodrigo44640006
137301         96oscarrip
138515        tanhowehowe
138730     maskelizorro23
Name: dst, dtype: object
101678         mr_songoku
103878    chiragg58858917
104964          alexmcl04
137422           _baylex_
Name: dst, dtype: object
12049     vigilantcrypto1
119841           i_wijaks
Name: dst, dtype: object
3395        sweetmilk1234
3939       shiltoncharles
4777         theunlucky1_
16277       happyfriend30
17102            qryptick
18148      doncoinleone52
19257          dajumpman1
19558         ottoman3401
24462         huberkevin1
30965            shabah20
53484       seyit52074894
54003            nnnndyyy
136917          4ir_alpha
139722            mandivs
140954        wolf_of_btc
142039        crypto__era
142040        meirelawson
143284    punishedrippler
154824        giveitpeace
159842      chunkyninja80
162257     manny_sandhuej
162447      cryptostackin
169621     cryptoschmoney
169796    hathormaximali1
171018      cryptovikingr
Name: dst, dtype: object
21752    skishor28698276
31219    bubble_boi_7883
Name: dst, dtype: object
20744         skishor91066534
140996         moonboysociety
172890    [twitter_query=btc]
Name: dst, dtype: object
13662    btc_holders
Name: dst, dtype: object
95439    megabigwinctyx
Name: dst, dtype: object
150960    btc_borghini
Name: dst, dtype: object
58551    beta_arq
Name: dst, dtype: object
74163    estrell68163801
Name: dst, dtype: object
3394          bbull4you
14406      vipjujubrais
31769       candyassvip
49115     hotassedbabes
50742         slutttris
135125          junona0
136498         amagabee
Name: dst, dtype: object
162898    chanthakim1
Name: dst, dtype: object
98963    mrturnip_head
Name: dst, dtype: object
30714     unlocknewhouse
34762           longsats
169059         marievh01
Name: dst, dtype: object
64628      ztxnbn
74606    anika_ir
Name: dst, dtype: object
29047    1e9petrichor
Name: dst, dtype: object
31781    maaran508
Name: dst, dtype: object
16365    snwmantreefiddy
22640      stefzcassia23
52187    longtermvisionn
Name: dst, dtype: object
75630    remybroun
Name: dst, dtype: object
152765    izzybolden
Name: dst, dtype: object
41292    fct_legion
Name: dst, dtype: object
2791            stefzcassia23
157079             22sal7850a
168430    [twitter_query=btc]
Name: dst, dtype: object
18978    skishor28698276
Name: dst, dtype: object
41213    mahadheer18
Name: dst, dtype: object
71142     cloudkaiwiz
142809        hatz772
Name: dst, dtype: object
64600       azharhayati84
173951    _pronosticator_
Name: dst, dtype: object
125873    erif70262968
Name: dst, dtype: object
116666    thecryptoround1
Name: dst, dtype: object
8070       sethi_milind
30412            iogitm
126579    samanthony327
129671    lentonmontejo
Name: dst, dtype: object
123487    tumisangchosha1
Name: dst, dtype: object
77214    btc_passo_passo
Name: dst, dtype: object
153276    ahmedjik
167423     ank_ont
Name: dst, dtype: object
77918    nfttrillion
Name: dst, dtype: object
721    klever_emy
Name: dst, dtype: object
25982     mohamme46587456
78116          twsaleh183
166614    antipet82704372
Name: dst, dtype: object
146751    ibehsuccess2
Name: dst, dtype: object
132785    ineedasupersuit
Name: dst, dtype: object
99359     romuloalcanfor
102763           jefflps
105242        md92023026
131590       tarekksobhy
132408    harasimowicz_p
155532          dsarteke
Name: dst, dtype: object
147495    gsccrypt
Name: dst, dtype: object

165357    akidd72
Name: dst, dtype: object
118728    ria32771936
Name: dst, dtype: object
20525    joemr13
Name: dst, dtype: object
99427     tdigitalfuture
166759            ehejno
Name: dst, dtype: object
9439    aydakeyhani
Name: dst, dtype: object
55156        healthy_pockets
71996            subterfugia
85297    [twitter_query=btc]
Name: dst, dtype: object
534             shiborgtoken
28913           rewardsbunny
31576    [twitter_query=btc]
35368              pipippoow
Name: dst, dtype: object
377      [twitter_query=btc]
13537            ainorin2021
34681           yuri_bo_life
Name: dst, dtype: object
55102           cristian_is_c
61609                 binance
71316                wsgtoken
75031               lrhanyeri
76152     [twitter_query=btc]
153174              lrhanyeri
159309    [twitter_query=btc]
171803           babydogecoin
Name: dst, dtype: object
845                 semil0re
1379                 burr_69
10185    [twitter_query=btc]
25149          theguycrypto1
27577                 404t2k
29725             wagmiradio
30007        rollnwthehomies
33498                garyvee
45623              bully_btc
52509          cryptoheadies
53045              sharifaee
Name: dst, dtype: object
55179          johanspauline
83416    [twitter_query=btc]
87464           lewiczmichal
97010         123savosavo123
Name: dst, dtype: object
696      [twitter_query=btc]
31191              nikichain
44576               nik2know
51818           cardano_fans
53447             winkorg777
Name: dst, dtype: object
55295            mintclubpro
67471            aofexglobal
74122               hseem786
96130    [twitter_query=btc]
Name: dst, dtype: object
55356    [twitter_query=btc]
74187             bitployapp
95988              remybroun
Name: dst, dtype: object
98043               _bombbabe
121221    [twitter_query=btc]
147221                mpj_btc
Name: dst, dtype: object
1067     [twitter_query=btc]
23464           nataliecityx
36748             thealtlord
49713        mexcderivatives
Name: dst, dtype: object
10441             miles2high
38460           lijingshanhe
55613             mrraptured
55818                llluo_1
57326         jordan01649999
58816                bywuyue
60055               rbxtoken
62325               mxstoken
63181        63657ojntezrlxc
63415    [twitter_query=btc]
64480          boxer_samurai
64481             usakenshin
69029           eley_samurai
70078         behrangsamurai
70728        mohamadsamurai3
75553          ehsansamuraei
77473        hunter_samurai1
79386        mamba2448185103
79805         sohylasamurai2
87019        okami_mxsamurai
87879              ugoprince
91106        steven_samurai5
92604        berlin_samurai2
93028        wolfofcryptoblv
93470               cyclin23
93471          dorsa___noble
96013        hossein_samurai
96997             holder_san
Name: dst, dtype: object
139347             detafollow
142586            themooncarl
160199    [twitter_query=btc]
Name: dst, dtype: object
55815                 313jui
57748                 imfhd7
58611                 baw_26
59633                 smpti0
65372                 thr815
67097        brahima89793080
67555                  soxcn
79592                 09shu0
79802                 hus_n8
80667                  78zp6
80668                 klaa_0
83175                 _hm_ri
84011                 0adii1
87014                 sf786i
87672                  pk50k
87874                  1aw55
89816                 a_q_59
94519    [twitter_query=btc]
94520                sn__owy
96205                  8_rif
96421                  sqb27
Name: dst, dtype: object
139569          mad_maxcrypto
174894    [twitter_query=btc]
Name: dst, dtype: object
98481         davidgokhshtein
102307    [twitter_query=btc]
121224        abdurra30475201
Name: dst, dtype: object
139825         yigit893027443
161798           traderyigitt
166998    [twitter_query=btc]
Name: dst, dtype: object
139910    [twitter_query=btc]
141489          csaszarphotos
173585         doncoinleone52
Name: dst, dtype: object
1820                eyn_2012
39146    [twitter_query=btc]
Name: dst, dtype: object
1763     [twitter_query=btc]
24979               elonmusk
31725                   jack
42912            bambam_1745
47438            _spiriitual
Name: dst, dtype: object
98964     [twitter_query=btc]
100762            knox_trades
109860        genuinearticles
111939              honey_btc
121073        galacticgeckosg
Name: dst, dtype: object
99234               hoppmoney
107806          hangloose1337
120938             rizostonks
123835             manyfcdgod
129174    [twitter_query=btc]
136788              gambiste1
Name: dst, dtype: object
140450    [twitter_query=btc]
145045              grimace85
174095            bpalaghia95
Name: dst, dtype: object
56814        bitmartexchange
66822    [twitter_query=btc]
73710           legit2point0
96752             netyaygara
Name: dst, dtype: object
99512          coindoktorunuz
107685            byscarface1
111645    [twitter_query=btc]
120132             aaydontnow
Name: dst, dtype: object
140601               devchart
146145        bartomi01551740
168486    [twitter_query=btc]
Name: dst, dtype: object
2795               ethprince
18588    [twitter_query=btc]
21383          papayapaya_fx
50070        58scpdvzaxqjw1g
Name: dst, dtype: object
57232               imamaz16
67475    [twitter_query=btc]
95466             nft_yooshi
Name: dst, dtype: object
99848            tazapatacoin
102659    [twitter_query=btc]
127325            misstraderr
Name: dst, dtype: object
3507     [twitter_query=btc]
9614              cryptosfun
46188           selmanbilgen
Name: dst, dtype: object
3387          degen_eggplant
48855              galaxybtc
54249    [twitter_query=btc]
Name: dst, dtype: object
3402     [twitter_query=btc]
19858          bitgameglobal
40802            fazlerabby0
Name: dst, dtype: object
100193              hypergemm
114846                 sdfwmn
121961        lbnnh9dfxhobwyl
127486            btc_magazin
132230    [twitter_query=btc]
Name: dst, dtype: object
57753            afro__fairy
67098                tomadjo
69860    [twitter_query=btc]
73085           bullishchief
75989           trippledutch
82104         mnwsupplychain
83598               robzy369
83786         wolfycryptoman
88702                markmnw
90288            crypto_lism
Name: dst, dtype: object
3740     [twitter_query=btc]
14208               richshib
18491          shibainfinity
40866                 msud84
Name: dst, dtype: object
57725              realrhy7hm
69227     [twitter_query=btc]
71575           orbit_crypto_
73052         cryptodutchie13
111794            pancakeswap
111994            babycakebsc
126065             realrhy7hm
128954    [twitter_query=btc]
135780        thebabycakearmy
Name: dst, dtype: object
3705     [twitter_query=btc]
29365           jkdgcityxwin
37553           rewardsbunny
Name: dst, dtype: object
57653           fani33142828
84538           santainu_bsc
85212    [twitter_query=btc]
Name: dst, dtype: object
100330               coinwarz
121907                bitcoin
126797    [twitter_query=btc]
Name: dst, dtype: object
141411    [twitter_query=btc]
147182          knowledge3307
163673            veysel56561
Name: dst, dtype: object
4366              vkarahan80
39015             ekoanalizz
49771    [twitter_query=btc]
Name: dst, dtype: object
141510        hamidrezasabery
141882    [twitter_query=btc]
147273              shibtoken
147456        pascal_kardinal
159487           babydogecoin
Name: dst, dtype: object
100794            narbtrading
114004    [twitter_query=btc]
134094          littlestarfit
Name: dst, dtype: object
18865     [twitter_query=btc]
21100              bonustiime
36001             cryptoboltx
37116                  ysnkts
100863                 ysnkts
103271            myteamchain
108233            btc_magazin
123434          mycmyteamcoin
130688    [twitter_query=btc]
Name: dst, dtype: object
4620         guruprasadvenk1
13170    [twitter_query=btc]
26796          thomasbernard
Name: dst, dtype: object
58491         cryptowhales00
96708    [twitter_query=btc]
Name: dst, dtype: object
125467            taurocrypto
135021    [twitter_query=btc]
142115            taurocrypto
171843    [twitter_query=btc]
Name: dst, dtype: object
142101              grimace85
147164          rhodes_crypto
148970    [twitter_query=btc]
Name: dst, dtype: object
5111              bitcoincom
10101        maharan66592188
48913    [twitter_query=btc]
Name: dst, dtype: object
5550                 anaacut
15947    [twitter_query=btc]
43168         realakamaruinu
49333             inusaitama
50412        cryptotweetybee
Name: dst, dtype: object
59149            lunionterra
75473    [twitter_query=btc]
75897          bitgameglobal
85019         tunefmofficial
89304            kharisma560
92949           cryptosantax
Name: dst, dtype: object
59402            pau_dennise
84391         genius_crypto_
89558    [twitter_query=btc]
Name: dst, dtype: object

5999          doncoinleone52
9101           rghaffarzadeh
25116    [twitter_query=btc]
38429              kojisensi
45886           realflokiinu
Name: dst, dtype: object
59412         criptogeronimo
61870    [twitter_query=btc]
77894            reinaldojhb
Name: dst, dtype: object
59347         cryptoinvest__
81625    [twitter_query=btc]
87151          jahrasta97400
Name: dst, dtype: object
101971    [twitter_query=btc]
114591            growmoneyde
116321         parabolic_matt
118952         lordmarkcrypto
122910        intocryptoverse
Name: dst, dtype: object
6458     [twitter_query=btc]
33887            fantomacorn
43789               rootdubs
Name: dst, dtype: object
59708          ashevchenko_7
83036           kriptozeryan
95403    [twitter_query=btc]
Name: dst, dtype: object
60009    [twitter_query=btc]
64026        afifarawnaf2017
65966             nft_yooshi
78505          mdalifrobbani
92078             nil_jonson
94893            metaplexbot
Name: dst, dtype: object
12511              bitcoincom
18161     [twitter_query=btc]
53512                  ilizhi
102397    [twitter_query=btc]
129943              cryptohsx
131803                 ilizhi
136315               jofromko
Name: dst, dtype: object
7742           cryptoyeager_
12178         ameen_muhammab
20892    [twitter_query=btc]
23066           babydogecoin
Name: dst, dtype: object
7899              kriptokusuu
7900                 xtrendci
16065            robinhoodcry
21834         cryptobarborose
22635             cryptokursu
41686           nazarioishere
44686     [twitter_query=btc]
49714            kriptoadam48
121775    [twitter_query=btc]
123612          nazarioishere
125437              hypergemm
Name: dst, dtype: object
103222              numan4670
108394            byscarface1
133336         coindoktorunuz
135765    [twitter_query=btc]
Name: dst, dtype: object
103358               metavpad
111481              crytojose
124971                 bscpad
131582    [twitter_query=btc]
133267         adapadofficial
Name: dst, dtype: object
144029    [twitter_query=btc]
149660           kripto_joker
155767                 kebafb
Name: dst, dtype: object
8066            bitcoinagile
14904    [twitter_query=btc]
18374             boba_73647
18375         delta_exchange
45114               bitbandz
Name: dst, dtype: object
144256             inusaitama
160101    [twitter_query=btc]
161781           saitamaangel
171471          teklopxcrypto
172212              cryptocom
Name: dst, dtype: object
8457            rewardsbunny
22089    [twitter_query=btc]
30503             lnsaniyah1
Name: dst, dtype: object
8424          vramillionaire
19294            hbl94761470
53503    [twitter_query=btc]
Name: dst, dtype: object
61481                 notxeb
78956         yusuke19088038
88936    [twitter_query=btc]
Name: dst, dtype: object
8704               famouzent
25626    [twitter_query=btc]
51586             terrapadtp
Name: dst, dtype: object
103727                 as12ey
118687            byscarface1
121028    [twitter_query=btc]
135866         coindoktorunuz
Name: dst, dtype: object
61897    [twitter_query=btc]
82969               huffpost
83396              eureuters
90068            twanflorijn
Name: dst, dtype: object
144686         safemoonspyros
157131           beyondastars
165044    [twitter_query=btc]
Name: dst, dtype: object
104209               elonmusk
113739    [twitter_query=btc]
116696                 saylor
136499              dr_marton
Name: dst, dtype: object
104506         sarahsilva6402
105318    [twitter_query=btc]
110555            inesrebelop
Name: dst, dtype: object

KeyboardInterrupt:

In [16]:
user_to_user_time_series[user_to_user_time_series['src'] == 'santa_coins']

,src,dst,messages_sent,messages_received,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges,sentiment_avg,emotionality_avg,complexity_avg,start_time_,end_time_
56008,santa_coins,rosellagirl87,0,2,2,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
58354,santa_coins,anglepori211,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
69429,santa_coins,lastyourk,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
70052,santa_coins,jeniiiiferrrr,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
75737,santa_coins,710nishan,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
78527,santa_coins,banduravik,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
79142,santa_coins,bitcoinlover1,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
87857,santa_coins,8nheer,0,2,2,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
89798,santa_coins,santa_coins,1,1,2,0.0,NaN,NaN,NaN,NaN,0.803255,0.196940,5.596566,2021-12-03 00:00:00,2021-12-10 00:00:00
90693,santa_coins,[twitter_query=btc],1,1,2,0.0,NaN,NaN,0.0,1.0,0.803255,0.196940,5.596566,2021-12-03 00:00:00,2021-12-10 00:00:00
90694,santa_coins,aslam89888,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
91084,santa_coins,zawalpoma,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
92809,santa_coins,ahmadfauzan73,0,2,2,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-03 00:00:00,2021-12-10 00:00:00
153595,santa_coins,nirmaldarshana3,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-26 00:00:00,2021-12-03 00:00:00
175576,santa_coins,santa_coins,1,1,2,0.0,NaN,NaN,NaN,NaN,0.991211,0.295401,6.576543,2021-11-12 00:00:00,2021-11-19 00:00:00
175592,santa_coins,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.991211,0.295401,6.576543,2021-11-12 00:00:00,2021-11-19 00:00:00

In [8]:
user_df = time_series[["id"]].copy()

# preprocessing
user_df.drop_duplicates(inplace=True)
user_df

                    id
0          aynenbeeyza
1           kriptocum4
2         bitcoinbased
3      stacktistic_btc
4            opporeno2
...                ...
41352         idsbraam
41353   mrandersonsays
41354       duncangray
41357      scooterdawg
41360  beamarq14614987

[37062 rows x 1 columns]

In [9]:
# build adj_mat construct
adj_mat_df = user_df.copy()
adj_mat_df.set_index("id", inplace=True)
adj_mat_df

Empty DataFrame
Columns: []
Index: [aynenbeeyza, kriptocum4, bitcoinbased, stacktistic_btc, opporeno2, coochm11, humblwarrior81, mooringaa3, magggiiiieee, maxxchewning, jektonft, qanda7272, daviddepaul10, alejandrosacias, 35izmirlili35, eos1894, clementwoof, mamat_cil, giet_maul16, bill09945892, okkasarry12, hafeezzargar4, drlovenstein, andrads30, scorpions_t, cot_criptomoeda, luckyybanggarrr, o52yl11fwciper5, twetch40880, mz_silenttearz, mavishfernande1, pashankara, drogondrakarys, winscityx112990, birumenangg, charles46301154, robostopia, thacashous1, skatygarcia, orenj0e, cryptonatical86, crypticcityx, jodin_the_meme, crystalraynor5, matthews_trace, zahraa_nia, chaudhry1300, salmenalnemer, hexstreamers, 60fps24, luckyhearty, sougo_shien6, black_bulll, carp1551, benjoesangalang, voodooroo, buddhadevgiri11, toxicdegen, thunder_meat, cryptonette1, rida09240916, tsuyopon_u3, herry_ploo, kriptoada1, delta____wither, risma92758840, shibainutoken_, hungarian_bitch, mdagli2003, 1903noiraigle, nikbinaz, amihaninj, time_money_, saip_yasar, dorayan_f, cryptowisper, deniz76829428, roadtoserfdom3, daancrypto, darr99962884, gfahim1982, brazilamericas, nofear07860922, coin100_, rasonlytrade, efecelikler, runescrypto, putramosap, rendy_sanja, janstabares, dwi_adhliza, izumifaiz, e1liotrades, gldnbluedeep, coudronmattias, lelawati1502, john57075146, bengbills, leone4812, zaqpar1, ...]

[37062 rows x 0 columns]

In [10]:
adj_mat_df_cols = adj_mat_df.transpose()

In [11]:
adj_mat_df_cols["name"] = user_df["id"].copy()
adj_mat_df_cols.set_index('name', inplace=True)

If link between nodes -> 1
If no link between nodes -> 0

In [13]:
adj_mat_df_cols

id,aynenbeeyza,kriptocum4,bitcoinbased,stacktistic_btc,opporeno2,coochm11,humblwarrior81,mooringaa3,magggiiiieee,maxxchewning,...,anoyingkarennft,cryptorevoltfr,b_programmers,gzlrofficial,mvanhaar,idsbraam,mrandersonsays,duncangray,scooterdawg,beamarq14614987
name,,,,,,,,,,,,,,,,,,,,,
aynenbeeyza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
kriptocum4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bitcoinbased,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stacktistic_btc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
opporeno2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
idsbraam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mrandersonsays,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duncangray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scooterdawg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
beamarq14614987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
adj_mat_df_cols.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37062 entries, aynenbeeyza to beamarq14614987
Columns: 37062 entries, aynenbeeyza to beamarq14614987
dtypes: float64(37062)
memory usage: 10.2+ GB