In [7]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [8]:
network_time_series = pd.read_csv('network_time_series.csv')
network_time_series

    number_of_edges  number_of_nodes          start_time_            end_time_
0               133               51  2021-10-22 00:00:00  2021-10-29 00:00:00
1                 7                3  2021-04-09 00:00:00  2021-04-16 00:00:00
2                 3                2  2020-09-25 00:00:00  2020-10-02 00:00:00
3                18                6  2021-10-01 00:00:00  2021-10-08 00:00:00
4                 3                2  2021-05-07 00:00:00  2021-05-14 00:00:00
5                34               13  2021-11-12 00:00:00  2021-11-19 00:00:00
6                 3                2  2020-11-20 00:00:00  2020-11-27 00:00:00
7                 6                3  2021-05-28 00:00:00  2021-06-04 00:00:00
8                 4                3  2021-07-30 00:00:00  2021-08-06 00:00:00
9                11                6  2021-09-10 00:00:00  2021-09-17 00:00:00
10                3                2  2021-08-20 00:00:00  2021-08-27 00:00:00
11                3                2  2021-08-13 00:00:00  2021-08-20 00:00:00
12                6                3  2021-09-17 00:00:00  2021-09-24 00:00:00
13                6                3  2021-03-26 00:00:00  2021-04-02 00:00:00
14            44227            10137  2021-12-03 00:00:00  2021-12-10 00:00:00
15                3                2  2021-06-11 00:00:00  2021-06-18 00:00:00
16               31               12  2021-10-15 00:00:00  2021-10-22 00:00:00
17               92               33  2021-11-19 00:00:00  2021-11-26 00:00:00
18                3                2  2021-03-12 00:00:00  2021-03-19 00:00:00
19            44019             9313  2021-11-05 00:00:00  2021-11-12 00:00:00
20                3                2  2021-06-04 00:00:00  2021-06-11 00:00:00
21                4                3  2020-02-21 00:00:00  2020-02-28 00:00:00
22               11                6  2021-09-24 00:00:00  2021-10-01 00:00:00
23                3                2  2021-07-09 00:00:00  2021-07-16 00:00:00
24                8                5  2021-06-25 00:00:00  2021-07-02 00:00:00
25                3                2  2021-04-02 00:00:00  2021-04-09 00:00:00
26                7                4  2021-09-03 00:00:00  2021-09-10 00:00:00
27                6                3  2021-08-27 00:00:00  2021-09-03 00:00:00
28            58559            12617  2021-10-29 00:00:00  2021-11-05 00:00:00
29                3                2  2020-07-03 00:00:00  2020-07-10 00:00:00
30                6                3  2021-07-16 00:00:00  2021-07-23 00:00:00
31            42103             9103  2021-11-26 00:00:00  2021-12-03 00:00:00
32                3                2  2020-04-24 00:00:00  2020-05-01 00:00:00
33               12                5  2021-10-08 00:00:00  2021-10-15 00:00:00
34                3                2  2021-02-05 00:00:00  2021-02-12 00:00:00

In [9]:
nodes = pd.read_csv('nodes.csv')
nodes

,id,favourites_count,followers_count,statuses_count,friends_count,twitter_query,name,original_dataset,listed_count,messages_sent,messages_received,out_degree,in_degree,degree,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges,domain,reach_2_out,reach_2,community_id,sentiment_avg,emotionality_avg,complexity_avg,betweenness,closeness,cluster,contribution_index_oscillation
0,0the_real_devil,16267,1205,11262,1094,BTC,LUCIFER 👑DANNY_FIRST_SON🧸👻,fetcher _ 20211128_BTC _ 20211128_BTC,8,1,1,2,2,4,2,0.00,0.0,1.0,NaN,NaN,NaN,28876,28877,community_1653,0.292684,0.144223,5.216487,0.000000,0.450283,cluster_1,0
1,0xblackwell,57,5,16,29,BTC,0xBlackwell,fetcher _ 20211128_BTC _ 20211128_BTC,0,1,1,3,2,5,2,0.00,0.0,1.0,NaN,NaN,NaN,28877,28877,community_1653,0.645656,0.148896,6.264551,235.647541,0.450294,cluster_1,0
2,15ugav9sfvufeps,351,13,264,42,BTC,Рост Ростовский,fetcher _ 20211128_BTC _ 20211128_BTC,1,1,1,3,2,5,2,0.00,NaN,NaN,0.0,1.0,NaN,28876,28877,community_1653,0.273811,0.207185,5.191489,0.000000,0.450289,cluster_1,0
3,3rdjanuary2009,2,0,1,246,BTC,A Chancellor on the brink ...,fetcher _ 20211128_BTC _ 20211128_BTC,0,1,1,3,2,5,2,0.00,0.0,1.0,NaN,NaN,NaN,28877,28877,community_1653,0.497630,0.163317,8.035519,1254.478261,0.450294,cluster_1,0
4,__cmc,14531,1909,10783,1090,BTC,Kadena Maxist ⛓🕸,fetcher _ 20211205_BTC _ 20211205_BTC,7,1,1,3,2,5,2,0.00,0.0,1.0,NaN,NaN,NaN,28877,28877,community_972,0.030062,0.256556,4.811678,28876.000000,0.450294,cluster_1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37057,vgxkronos,1125,143,415,154,BTC,Kronos,fetcher _ 20211128_BTC _ 20211128_BTC,1,1,1,3,2,5,2,0.00,0.0,1.0,NaN,NaN,NaN,28877,28877,community_1653,0.847652,0.232242,5.104983,14437.500000,0.450294,cluster_1,0
37058,vivianl66831951,1565,520,27719,1533,BTC,Vivian Lewis,fetcher _ 20211205_BTC _ 20211205_BTC,1,1,1,6,2,8,2,0.00,0.0,1.0,NaN,NaN,NaN,28877,28877,community_1653,0.999176,0.531777,9.827496,1667.075851,0.450310,cluster_1,0
37059,winnietessel,575,100,1083,261,BTC,Winnie,fetcher _ 20211031_BTC _ 20211031_BTC,0,1,1,4,2,6,2,0.00,0.0,1.0,NaN,NaN,NaN,28876,28877,community_1653,0.645656,0.148896,6.264551,0.000000,0.450294,cluster_1,0
37060,wombat85623246,3423,10,1485,24,BTC,Wombat,fetcher _ 20211128_BTC _ 20211128_BTC,0,1,2,2,3,5,3,-0.33,0.0,1.0,NaN,NaN,NaN,28876,28877,community_1653,0.024840,0.302173,6.488832,0.000000,0.450283,cluster_1,0
37061,xoxoxbanz,5295,203,26409,3135,BTC,🍀XOXO||free tag🍀,fetcher _ 20211031_BTC _ 20211031_BTC,3,1,1,3,2,5,2,0.00,NaN,NaN,0.0,1.0,NaN,28877,28877,community_1653,0.970673,0.319932,5.692192,73.425258,0.450294,cluster_1,0

In [10]:
time_series = pd.read_csv('time_series.csv')
time_series

,id,favourites_count,followers_count,statuses_count,friends_count,twitter_query,name,original_dataset,listed_count,messages_sent,messages_received,out_degree,in_degree,degree,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges,domain,reach_2_out,reach_2,community_id,sentiment_avg,emotionality_avg,complexity_avg,betweenness,closeness,cluster,contribution_index_oscillation,start_time_,end_time_
0,aynenbeeyza,5175,238,2334,243,BTC,beyza.,fetcher _ 20211205_BTC _ 20211205_BTC,5,1,1,3,2,5,2,0.00,0.000000,1.0,NaN,NaN,NaN,28877,28877,community_1653,0.061145,0.304475,11.461567,2061.642857,0.450294,cluster_1,0,2021-12-03 00:00:00,2021-12-10 00:00:00
1,kriptocum4,2586,11702,12462,121,BTC,👑 🅲🆁🆈🅿🆃🅾 🆁🅴🅸🆂 👑,fetcher _ 20211205_BTC _ 20211205_BTC,31,8,25,3,16,19,33,-0.52,0.126389,2.0,0.155324,1.333333,NaN,28883,28877,community_1653,0.775175,0.304228,10.973110,19.708777,0.450327,cluster_1,2,2021-11-26 00:00:00,2021-12-03 00:00:00
2,bitcoinbased,652,143,1189,544,BTC,Bitcoin Based,fetcher _ 20211031_BTC _ 20211031_BTC,4,1,1,4,2,6,2,0.00,NaN,NaN,0.000000,1.000000,NaN,28877,28877,community_1653,0.610494,0.158284,5.408799,28876.000000,0.450300,cluster_0,0,2021-10-29 00:00:00,2021-11-05 00:00:00
3,stacktistic_btc,543,538,463,876,BTC,STACKTISTICS.btc 🎫,fetcher _ 20211205_BTC _ 20211205_BTC,8,8,13,13,5,18,21,-0.24,0.015722,1.6,0.012111,1.400000,NaN,28885,28877,community_1653,0.555073,0.165025,5.106082,188661.166667,0.450393,cluster_2,0,2021-12-03 00:00:00,2021-12-10 00:00:00
4,opporeno2,11208,296,4080,815,BTC,比特币-百舸争流,fetcher _ 20211031_BTC _ 20211031_BTC,5,2,2,3,2,5,4,0.00,0.558056,1.0,0.000000,1.000000,NaN,28877,28877,community_1653,0.645656,0.148896,6.264551,9624.666667,0.450294,cluster_1,0,2021-10-29 00:00:00,2021-11-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41356,btc_bomber,0,0,0,0,BTC,桜囲章一⚛️仮想通貨,fetcher _ 20211205_BTC _ 20211205_BTC,0,0,2,0,2,2,2,-1.00,NaN,NaN,NaN,NaN,NaN,0,3,community_2720,NaN,NaN,NaN,0.000000,0.000000,cluster_1,0,2021-12-03 00:00:00,2021-12-10 00:00:00
41357,scooterdawg,0,0,0,0,BTC,Kevin B. #KeepVirginiaBlue,fetcher _ 20211031_BTC _ 20211031_BTC,0,0,1,0,1,1,1,-1.00,NaN,NaN,NaN,NaN,NaN,0,4,community_395,NaN,NaN,NaN,0.000000,0.000000,cluster_0,0,2021-10-29 00:00:00,2021-11-05 00:00:00
41358,xshibanu,0,0,0,0,BTC,XShibanu,fetcher _ 20211205_BTC _ 20211205_BTC,0,0,57,0,49,49,57,-1.00,NaN,NaN,NaN,NaN,NaN,0,50,community_1653,NaN,NaN,NaN,0.000000,0.000000,cluster_1,0,2021-11-26 00:00:00,2021-12-03 00:00:00
41359,cryptoboyka1,0,0,0,0,BTC,Crypto Boyka,fetcher _ 20211107_BTC_20211107_BTC,0,1,2,2,3,5,3,-0.33,0.000000,1.0,NaN,NaN,NaN,28876,28877,community_1653,0.930703,0.386621,8.652434,0.000000,0.450283,cluster_1,0,2021-11-05 00:00:00,2021-11-12 00:00:00
41360,beamarq14614987,0,0,0,0,BTC,Bea Marquez,fetcher _ 20211205_BTC _ 20211205_BTC,0,0,1,0,1,1,1,-1.00,NaN,NaN,NaN,NaN,NaN,0,2,community_530,NaN,NaN,NaN,0.000000,0.000000,cluster_1,0,2021-12-03 00:00:00,2021-12-10 00:00:00

In [11]:
user_to_user = pd.read_csv('user_to_user.csv')
user_to_user

,src,dst,messages_sent,messages_received,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges
0,0xgianni,coingecko,1,0,1,1.0,NaN,NaN,NaN,NaN
1,0xr2_,rektcapital,1,0,1,1.0,NaN,NaN,NaN,NaN
2,13thcryptotitan,13thcryptotitan,1,1,2,0.0,NaN,NaN,NaN,NaN
3,21_millie_btc,[twitter_query=btc],1,1,2,0.0,NaN,NaN,0.0,1.0
4,2bosquez4,2bosquez4,1,1,2,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
168811,yy55088169,cryptofinally,1,0,1,1.0,NaN,NaN,NaN,NaN
168812,zgrdurm92493156,eskiyeniyatirim,1,0,1,1.0,NaN,NaN,NaN,NaN
168813,zidanezizo122,mhmdgenral,0,2,2,-1.0,NaN,NaN,NaN,NaN
168814,zuri05622973,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN
168815,zzbkmzz,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN

In [12]:
user_to_user_time_series = pd.read_csv('user_to_user_time_series.csv')
user_to_user_time_series

,src,dst,messages_sent,messages_received,messages_total,contribution_index,ego_art,ego_nudges,alter_art,alter_nudges,sentiment_avg,emotionality_avg,complexity_avg,start_time_,end_time_
0,beconomy_hq,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.836148,0.281494,5.119517,2020-02-21 00:00:00,2020-02-28 00:00:00
1,truthraiderhq,beconomy_hq,0,1,1,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-21 00:00:00,2020-02-28 00:00:00
2,beconomy_hq,beconomy_hq,1,1,2,0.0,NaN,NaN,NaN,NaN,0.836148,0.281494,5.119517,2020-02-21 00:00:00,2020-02-28 00:00:00
3,beconomy_hq,truthraiderhq,1,0,1,1.0,NaN,NaN,NaN,NaN,0.836148,0.281494,5.119517,2020-02-21 00:00:00,2020-02-28 00:00:00
4,[twitter_query=btc],beconomy_hq,1,1,2,0.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,2020-02-21 00:00:00,2020-02-28 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175590,trading_peter,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.838159,0.193055,5.924200,2021-11-12 00:00:00,2021-11-19 00:00:00
175591,dogsofelon,dogsofelon,1,1,2,0.0,NaN,NaN,NaN,NaN,0.639133,0.121849,5.240852,2021-11-12 00:00:00,2021-11-19 00:00:00
175592,santa_coins,[twitter_query=btc],1,1,2,0.0,0.0,1.0,NaN,NaN,0.991211,0.295401,6.576543,2021-11-12 00:00:00,2021-11-19 00:00:00
175593,armando_aml,armando_aml,1,1,2,0.0,NaN,NaN,NaN,NaN,0.958465,0.198134,6.362594,2021-11-12 00:00:00,2021-11-19 00:00:00
175594,cryptokunstler,cryptokunstler,1,1,2,0.0,NaN,NaN,NaN,NaN,0.928048,0.276091,9.097756,2021-11-12 00:00:00,2021-11-19 00:00:00